const messages = {
  USER_CREATED_SUCCESSFULLY: "User Register & Otp Sent Successfully.",
  USER_ALREADY_EXISTS: "User Already Exists.",
  USER_NOT_FOUND: "User Not Found.",
  INVALID_CREDENTIALS: "Invalid Credentials",
  PASSWORD_RESET_SUCCESS: "Password Set Successfully.",
  INVALID_OLD_PASSWORD: "Invalid Old Password",
  PASSWORD_NOT_MATCH: "New Password & Confirm Password Not Matched",
  NEW_PASSWORD_SAME_AS_OLD: "Old Password & New Password Not Same",
  PASSWORD_UPDATED_SUCCESSFULLY: "Password Updated Successfully",
  INTERNAL_SERVER_ERROR: "Internal Server Error",
  UNAUTHORIZED_ACCESS: "Unauthorized Access",
  FORBIDDEN_ACCESS: "You do not have permission to access this resource.",
  DATA_CONFLICT: "There is a conflict with the existing data.",
  BAD_REQUEST: "Bad Request",
  PASSWORD_NOT_MATCHED: "Password does not match!",
  LOGIN_SUCCESSFUL: "Login Successful!",
  MISSING_FIELDS: "All fields are required.",
  OTP_SENT_SUCCESSFULLY: "Otp Send Seccessfully",
  OTP_VERIFIED_SUCCESSFULLY: "Otp Verify Successfully",
  OTP_RESENT_SUCCESSFULLY: "Otp Resend Successfully",
  INVALID_OTP: "Invalid Otp",
  OTP_RECORD_NOT_FOUND: "Otp Not Found",
  EXPIRED_OTP: "Otp Expired",
  PASSWORD_RESET_SUCCESSFUL: "Password Reset Successfully",
  DETAILS_FETCHED: "Details Fetched Successfully",
  PROFILE_UPDATED_SUCCESSFULLY: "Profile Updated Successfully",
};

module.exports = messages;
